version: '3.8'
services:
  my-app:
    build:
      context: .
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: postgres
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5438:5432"