version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "8080:8080" # Пробрасываем порт для доступа к приложению
    depends_on:
      - db # Зависимость от сервиса базы данных
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "mysecretpassword"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "postgres"
      DB_SSLMODE: "disable"

  db:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - "5438:5432" # Пробрасываем порт для доступа к базе с хоста
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Сохраняем данные базы между перезапусками контейнера

volumes:
  postgres-data: