version: '3.8'

services:
  rest-api:
    build: ./
    command: ./wait-for-postgres.sh db ./rest-api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=mysecretpassword

  db:
    restart: always
    image: postgres:17.0
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5436:5432